# Generated by Django 3.1.5 on 2021-01-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='publicacion',
            field=models.DateTimeField(),
        ),
    ]
