# Generated by Django 3.1.5 on 2021-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_auto_20210120_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='direccion',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
