# Generated by Django 3.1.5 on 2021-01-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_prestamo_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='prestado',
            field=models.BooleanField(default=False),
        ),
    ]
