# Generated by Django 3.1.5 on 2021-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_prestamo_prestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='prestado',
            field=models.BooleanField(default=True),
        ),
    ]
