# Generated by Django 3.1.5 on 2021-01-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_auto_20210121_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='prestado',
        ),
        migrations.AddField(
            model_name='libro',
            name='prestado',
            field=models.BooleanField(default=False),
        ),
    ]
