# Generated by Django 3.1.5 on 2021-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0009_auto_20210121_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='veces_prestado',
            field=models.IntegerField(default=0),
        ),
    ]
